version: '3'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    hostname: cassandra
    ports:
      - 9042:9042
    environment:
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra
    volumes:
      - ./home:/home
      - cassandra-data:/var/lib/cassandra
    networks:
      - cassandra-network

volumes:
  cassandra-data:

networks:
  cassandra-network:
    driver: bridge
